# -------------------------------
# ConfigMap for productservice settings
# -------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: productservice-config
data:
  FrontendUrl: "http://localhost:5173,http://192.168.49.2:5173,http://host.minikube.internal:5173"
  TypeSense__Host: "host.minikube.internal"
  TypeSense__ApiKey: "xyz"
  TypeSense__Protocol: "http"
  TypeSense__Port: "8108"
  Kafka__Server: "host.minikube.internal:9095"
  Jwt__Key: "YourSecretKeyForAuthenticationOfApplication"
  Jwt__Issuer: "yourCompanyIssuer.com"
  Jwt__Audience: "yourCompanyAudience.com"
  Jwt__ExpiresIn: "3600"
  ConnectionStrings__DefaultConnection: "Host=host.minikube.internal:5432;Database=eshop_productservice;Username=postgres;Password=postgres;"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  AllowedHosts: "*"
---
# -------------------------------
# ConfigMap for userservice settings
# -------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
data:
  ConnectionStrings__DefaultConnection: "Host=host.minikube.internal:5433;Database=eshop_userservice;Username=postgres;Password=postgres;"
  Jwt__Key: "YourSecretKeyForAuthenticationOfApplication"
  Jwt__Issuer: "yourCompanyIssuer.com"
  Jwt__Audience: "yourCompanyAudience.com"
  Jwt__ExpiresIn: "3600"
  Jwt__RefreshTokenExpiresIn: "2592000"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  AllowedHosts: "*"
---
# -------------------------------
# ConfigMap for cartservice settings
# -------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: cartservice-config
data:
  ApiUrl: "http://productservice-service"
  Kafka__Server: "host.minikube.internal:9095"
  Kafka__GroupId: "cartservice-consumer-group"
  Jwt__Key: "YourSecretKeyForAuthenticationOfApplication"
  Jwt__Issuer: "yourCompanyIssuer.com"
  Jwt__Audience: "yourCompanyAudience.com"
  Jwt__ExpiresIn: "3600"
  eshop_cartservice__ConnectionString: "mongodb://host.minikube.internal:27017"
  eshop_cartservice__DatabaseName: "eshop_cartservice"
  eshop_cartservice__CartItemsCollectionName: "CartItems"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  AllowedHosts: "*"
---
# -------------------------------
# userservice Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: jensr22/eshop_userservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          envFrom:
            - configMapRef:
                name: userservice-config
---
# -------------------------------
# userservice Service
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
spec:
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
# -------------------------------
# productservice Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: jensr22/eshop_productservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          envFrom:
            - configMapRef:
                name: productservice-config
---
# -------------------------------
# productservice Service
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: productservice-service
spec:
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
# -------------------------------
# cartservice Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: jensr22/eshop_cartservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          envFrom:
            - configMapRef:
                name: cartservice-config
---
# -------------------------------
# cartservice Service
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: cartservice-service
spec:
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
# -------------------------------
# Ingress for path routing
# -------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api/productservice
            pathType: Prefix
            backend:
              service:
                name: productservice-service
                port:
                  number: 80
          - path: /api/userservice
            pathType: Prefix
            backend:
              service:
                name: userservice-service
                port:
                  number: 80
          - path: /api/cartservice
            pathType: Prefix
            backend:
              service:
                name: cartservice-service
                port:
                  number: 80