apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-productservice
  labels:
    app: eshop-productservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-productservice
  template:
    metadata:
      labels:
        app: eshop-productservice
    spec:
      containers:
        - name: eshop-productservice
          image: jensr22/eshop_productservice:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-productservice
spec:
  selector:
    app: eshop-productservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
