# -------------------------------
# userservice Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
 name: userservice-deployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: userservice
 template:
   metadata:
     labels:
       app: userservice
   spec:
     containers:
     - name: userservice
       image: jensr22/eshop_userservice:latest
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 8080
---
# -------------------------------
# userservice Service
# -------------------------------
apiVersion: v1
kind: Service
metadata:
 name: userservice-service
spec:
 selector:
   app: userservice
 ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
 type: ClusterIP

---
# -------------------------------
# productservice Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - name: productservice
        image: jensr22/eshop_productservice:latest
        ports:
        - containerPort: 8080
---
# -------------------------------
# productservice Service
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: productservice-service
spec:
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
# -------------------------------
# Ingress for path routing
# -------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      access_by_lua_block {
#          local jwt = require "resty.jwt"
#          local cjson = require "cjson"
#
#          local token = ngx.var.http_authorization
#          if token then
#              token = token:gsub("Bearer ", "")
#              local jwt_obj = jwt:verify("your_jwt_secret", token)
#
#              if jwt_obj.verified then
#                  local claims = jwt_obj.payload
#                  -- Forward specific claims as headers
#                  ngx.req.set_header("X-User-Id", claims.sub)
#                  ngx.req.set_header("X-User-Role", claims.role)
#              end
#          end
#      }
spec:
  rules:
  - http:
      paths:
      - path: /api/productservice
        pathType: Prefix
        backend:
          service:
            name: productservice-service
            port:
              number: 80
      - path: /api/userservice
        pathType: Prefix
        backend:
          service:
            name: userservice-service
            port:
              number: 80